### ISSUE TITLE
Cannot read property 'rss' of null

### ISSUE THREAD

**Issue by ghost** [MakhouT/treehouseDownloader#10]
Once installed & then run, the console says:

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'rss' of null
    at /Users/xxx/treehouseDownloader/download.js:22:31
    at Parser.<anonymous> (/Users/xxx/treehouseDownloader/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser.exports.Parser.Parser.parseString (/Users/xxx/treehouseDownloader/node_modules/xml2js/lib/xml2js.js:494:16)
    at Parser.parseString (/Users/xxx/treehouseDownloader/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/Users/xxx/treehouseDownloader/node_modules/xml2js/lib/xml2js.js:535:19)
    at IncomingMessage.<anonymous> (/Users/xxx/treehouseDownloader/download.js:21:4)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by MakhouT** [comment]
Which course did you try to download? It is working for me. I just did a new clone and it's working.

**Comment by ghost** [comment]
@MakhouT Thanks for the reply. I tried many course as I can, but all got the same error result currently. Also I tried to re-clone the git, but still failed. The funny thing is I could smoothly download courses via RSS links at the very beginning and the track download function still works but unstable. Anyway, I would try again.

p.s. I personally appreciate and love this fantastic tool! 👍

**Comment by MakhouT** [comment]
So it was working in the beginning? Did you update nodejs recently?
The track downloading is indeed a bit unstable, but I don't really have much time at the moment to have a look at it. But will look at it in the future.

Keep me updated when you try again.

I am happy to hear you like it!! :+1:

**Comment by ghost** [comment]
@MakhouT No worries at all, I hope I could find out and fix the issue by myself :) I tried to downgrade node from my current (6.0.0) to 5.xx stable, 4.xx stable and 0.12.xx stable, unfortunately none worked. I am still keep working on it, and I will always keep an eye on this great repo.

I hope you have a lovely day!

Cheers

**Comment by coderpradp** [comment]
@TLZAustralia Hey did you managed to reslove this?
