### ISSUE TITLE
Unhandled 'error'

### ISSUE THREAD

**Issue by raistael** [MakhouT/treehouseDownloader#18]
Seems that this package isn't being developed any longer, but if anyone digs around this might come in handy. When doing the 'npm install' a couple of the packages were warned as depricated and there was some 'repository' issue that one of the other issues already mentioned.
```
events.js:163
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'substring' of undefined
    at F:\TreehouseVideos\treehouseDownloader\download.js:40:58
    at Array.forEach (native)
    at F:\TreehouseVideos\treehouseDownloader\download.js:35:20
    at Parser.<anonymous> (F:\TreehouseVideos\treehouseDownloader\node_modules\xml2js\lib\xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:191:7)
    at SAXParser.onclosetag (F:\TreehouseVideos\treehouseDownloader\node_modules\xml2js\lib\xml2js.js:447:26)
    at emit (F:\TreehouseVideos\treehouseDownloader\node_modules\sax\lib\sax.js:640:35)
    at emitNode (F:\TreehouseVideos\treehouseDownloader\node_modules\sax\lib\sax.js:645:5)
    at closeTag (F:\TreehouseVideos\treehouseDownloader\node_modules\sax\lib\sax.js:905:7)
```
I'm guessing the information this app used is no longer valid in the newer iterations of Treehouse's setup.

**Comment by fishnibble** [comment]
Having the same issue :(
